name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Build and push
        run: |
          docker build . --tag ghcr.io/mperestoronin/mailman:latest
          docker push ghcr.io/mperestoronin/mailman:latest