name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Build and push
        run: |
          docker build . --tag ghcr.io/mperestoronin/mailman:latest
          docker push ghcr.io/mperestoronin/mailman:latest
  deploy:
    env:
      REPO: ${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Redeploy compose stack
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ~/media-corpus-classifier
            docker compose -f docker-compose.kafka.yml pull
            docker compose -f docker-compose.kafka.yml up -d --force-recreate --wait
            docker ps